jobs:
  windows:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    steps:
      - uses: ocaml/setup-ocaml@v3
        with:
          cache-prefix: v2
          ocaml-compiler: 5.3.0
          opam-pin: false
          save-opam-post-run: true
      - run: "dune build"
  ubuntu:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: ocaml/setup-ocaml@v3
        with:
          cache-prefix: v2
          ocaml-compiler: 5.3.0
          opam-pin: false
          save-opam-post-run: true
      - run: "dune build"
  macos:
    defaults:
      run:
        shell: bash
    runs-on: macos-latest
    steps:
      - uses: ocaml/setup-ocaml@v3
        with:
          cache-prefix: v2
          ocaml-compiler: 5.3.0
          opam-pin: false
          save-opam-post-run: true
      - run: "dune build"
name: ci
on:
  - push
