jobs:
  windows:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ocaml/setup-ocaml@v3
        with:
          cache-prefix: v2
          ocaml-compiler: 5.3.0
          opam-pin: false
          save-opam-post-run: true
      - run: | 
          opam install dune.3.20.0
          echo "yay"
          eval $(opam env)
          ./configure
          dune build
  ubuntu:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ocaml/setup-ocaml@v3
        with:
          cache-prefix: v2
          ocaml-compiler: 5.3.0
          opam-pin: false
          save-opam-post-run: true
      - run: | 
          opam install dune.3.20.0
          echo "yay"
          eval $(opam env)
          ./configure
          dune build
  macos:
    defaults:
      run:
        shell: bash
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ocaml/setup-ocaml@v3
        with:
          cache-prefix: v2
          ocaml-compiler: 5.3.0
          opam-pin: false
          save-opam-post-run: true
      - run: | 
          opam install dune.3.20.0
          echo "yay"
          eval $(opam env)
          ./configure
          dune build
name: ci
on:
  - push
